language: python
python:
- '2.7'
install:
- pip install .
- pip install -r requirements.txt
- pip install coveralls
script: coverage run --source satistjenesten setup.py test
after_succecss: coveralls
