language: python
python:
- '2.7'
before_install:
- sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -y
- sudo apt-get update -q
- sudo apt-get install libhdf5-serial-dev
- sudo apt-get install libnetcdf-dev
- sudo apt-get install libgdal-dev
- sudo apt-get install python-gdal

install:
- pip install .
- pip install -r requirements.txt
- pip install coveralls

script:
- coverage run --source satistjenesten setup.py test
- behave

after_success: coveralls
