language: python
python:
- '2.7'
before_install:
- sudo apt-get install libhdf5-serial-dev libnetcdf-dev

install:
- pip install .
- pip install -r requirements.txt
- pip install coveralls

script:
- coverage run --source satistjenesten setup.py test
- behave

after_success: coveralls
